Pandas - обязательная часть жизненного цикла Data science. Это самая популярная и широко используемая библиотека Python для науки о данных, наряду с NumPy, matplotlib. Pandas предоставляет быстрые и гибкие структуры данных, такие как dataframe и series, которые предназначены для очень простой и интуитивно понятной работы со структурированными данными.

Содержит:


*   Богатые функциональные возможности
*   Высокоуровневые структуры данных и инструменты манипулирования
*   ETL (извлечение, преобразование, загрузка) для преобразования и хранения данных. Имеет поддержку загрузки CSV-файлов, TXT-файлов, XLSX-файлов

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/Техн. и инстр. машинного обучения 1 сем/1 практика Python/Данные.csv',sep = ';')

In [ ]:
data

A   B   C
0  1   2   6
1  2   4  12
2  3   6  18
3  4   8  24
4  5  10  30
5  6  12  36
6  7  14  42
7  8  16  48
8  9  18  54

In [ ]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
print(data['A'])
print(type(data['A']))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: A, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
print(data[['A','C']])

   A   C
0  1   6
1  2  12
2  3  18
3  4  24
4  5  30
5  6  36
6  7  42
7  8  48
8  9  54


In [ ]:
print(data.columns)
print(data.index)
print(data.values)
print(type(data.values))

Index(['A', 'B', 'C'], dtype='object')
RangeIndex(start=0, stop=9, step=1)
[[ 1  2  6]
 [ 2  4 12]
 [ 3  6 18]
 [ 4  8 24]
 [ 5 10 30]
 [ 6 12 36]
 [ 7 14 42]
 [ 8 16 48]
 [ 9 18 54]]
<class 'numpy.ndarray'>


In [ ]:
print(data[data>=5])#вывод элементов больше или равным 2
print()
print(data[data['A']>=5])

     A     B   C
0  NaN   NaN   6
1  NaN   NaN  12
2  NaN   6.0  18
3  NaN   8.0  24
4  5.0  10.0  30
5  6.0  12.0  36
6  7.0  14.0  42
7  8.0  16.0  48
8  9.0  18.0  54

   A   B   C
4  5  10  30
5  6  12  36
6  7  14  42
7  8  16  48
8  9  18  54


In [ ]:
print(data.isna()) #проверка, есть ли пропуски

print(data[data>=5].isna().sum())

       A      B      C
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
A    4
B    2
C    0
dtype: int64


In [ ]:
data['D']=data['A']+data['B']+data['C']
print(data)

   A   B   C   D
0  1   2   6   9
1  2   4  12  18
2  3   6  18  27
3  4   8  24  36
4  5  10  30  45
5  6  12  36  54
6  7  14  42  63
7  8  16  48  72
8  9  18  54  81


In [ ]:
data[(data['B']>=8) & (data['C']<48)]

A   B   C   D
3  4   8  24  36
4  5  10  30  45
5  6  12  36  54
6  7  14  42  63

In [ ]:
print(data.loc[[0,1,4],['B','C']]) #выборка по названию
print()
print(data.iloc[[0,1,4],[1,2]]) #выборка по индексу

    B   C
0   2   6
1   4  12
4  10  30

    B   C
0   2   6
1   4  12
4  10  30


In [ ]:
# если указать не 0, а [0], то в результате будет не серия, а фрейм
print(data.loc[1], type(data.loc[1]))
print()
print(data.loc[[1]], type(data.loc[[1]]))

A     2
B     4
C    12
D    18
Name: 1, dtype: int64 <class 'pandas.core.series.Series'>

   A  B   C   D
1  2  4  12  18 <class 'pandas.core.frame.DataFrame'>


In [ ]:
# метод dublicate() указывает, какие строки явялются дубликатами
print(data.duplicated())

#можно удалить дубликаты
new_data1 = data[data.duplicated()==False]
# или
new_data2 = data.drop_duplicates() #удаление повтоярющихся строк

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool


In [ ]:
# еще один способ фильтрации -- это метод query()
data.query('A > 5 and B < 48') #команда для фильтрации пишется в ковычках в виде строки, в pandas можно писать sql запросы

A   B   C   D
5  6  12  36  54
6  7  14  42  63
7  8  16  48  72
8  9  18  54  81

In [ ]:
# .astype({'B':int}) привести датафрейм к дургому типу или только выбранные столбцы
data1 = data.astype({'B':float})
print(data1)

   A     B   C   D
0  1   2.0   6   9
1  2   4.0  12  18
2  3   6.0  18  27
3  4   8.0  24  36
4  5  10.0  30  45
5  6  12.0  36  54
6  7  14.0  42  63
7  8  16.0  48  72
8  9  18.0  54  81


In [ ]:
data.describe()

A          B          C          D
count  9.000000   9.000000   9.000000   9.000000
mean   5.000000  10.000000  30.000000  45.000000
std    2.738613   5.477226  16.431677  24.647515
min    1.000000   2.000000   6.000000   9.000000
25%    3.000000   6.000000  18.000000  27.000000
50%    5.000000  10.000000  30.000000  45.000000
75%    7.000000  14.000000  42.000000  63.000000
max    9.000000  18.000000  54.000000  81.000000

In [ ]:
data[data.iloc[:,1]<5]

A  B   C   D
0  1  2   6   9
1  2  4  12  18

In [ ]:
data['A'] < 5

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7    False
8    False
Name: A, dtype: bool

In [ ]:
data.iloc[:,0] < 5

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7    False
8    False
Name: A, dtype: bool

In [ ]:
def function(x,name):
    if x[name] < 5:
        x['new_column']=1
    else:
        x['new_column']=0
    return x

a=data.apply(function,axis = 1,args='A')
print(a)

   A   B   C   D  new_column
0  1   2   6   9           1
1  2   4  12  18           1
2  3   6  18  27           1
3  4   8  24  36           1
4  5  10  30  45           0
5  6  12  36  54           0
6  7  14  42  63           0
7  8  16  48  72           0
8  9  18  54  81           0


In [ ]:
data=data.rename({0:'000'}) #по умолчанию работает со строчками

In [ ]:
data=data.rename(columns={"C":"CC","B":"BB"})
data

A  BB  CC   D
000  1   2   6   9
1    2   4  12  18
2    3   6  18  27
3    4   8  24  36
4    5  10  30  45
5    6  12  36  54
6    7  14  42  63
7    8  16  48  72
8    9  18  54  81

In [ ]:
data.rename(columns=lambda x: x+'_1', inplace = True)

In [ ]:
data

A_1  BB_1  CC_1  D_1
000    1     2     6    9
1      2     4    12   18
2      3     6    18   27
3      4     8    24   36
4      5    10    30   45
5      6    12    36   54
6      7    14    42   63
7      8    16    48   72
8      9    18    54   81

In [ ]:
data.rename(index=lambda x: str(x)+'_1', inplace=True)

In [ ]:
data

A_1  BB_1  CC_1  D_1
000_1    1     2     6    9
1_1      2     4    12   18
2_1      3     6    18   27
3_1      4     8    24   36
4_1      5    10    30   45
5_1      6    12    36   54
6_1      7    14    42   63
7_1      8    16    48   72
8_1      9    18    54   81

In [ ]:
S = pd.Series(['Мышка','Нарушка'])
print(S)

0      Мышка
1    Нарушка
dtype: object


In [ ]:
print(S.index) #индексы
print(list(S.index)) #индексы
print(S.values) #список значений

RangeIndex(start=0, stop=2, step=1)
[0, 1]
['Мышка' 'Нарушка']


In [ ]:
#индексы можно задать ручками
new_s = pd.Series(S.values, index=['1','2'])
new_s['3']='Квакушка' #добавление нового значения
new_s['4']='Квакушка'
print(new_s)

1       Мышка
2     Нарушка
3    Квакушка
4    Квакушка
dtype: object


In [ ]:
#количество уникальных значений
new_s.value_counts()

Квакушка    2
Мышка       1
Нарушка     1
dtype: int64